### ISSUE TITLE
x86fre build is broken

### ISSUE THREAD

**Issue by CHOSTeam** [stephanosio/OpenNT-MinKernel#3]
When trying to build under x86fre, the hals and ntos build fails.
The error in the hals is: "ixmca.obj : warning LNK4217: locally defined symbol _HalpMcaSwitchMcaExceptionStackAndBugCheck@20 imported in function _HalpMcaExceptionHandler@0" followed by "link : error LNK1218: warning treated as error; no output file generated".
The error in the ntos is: "error LNK2001: unresolved external symbol __SEH_epilog"

**Comment by stephanosio** [comment]
I can reproduce this issue when building ntos and hals under x86fre. I will look into it.

**Comment by stephanosio** [comment]
The problem here is that x86fre compiles with /Oxs that performs maximum optimisation for smaller executable size; hence, making calls to SEH prolog/epilog functions rather than inline-ing it.

The quick-and-dirty solution to this problem would be to use /Ox instead of /Oxs in the NTOSBE x86fre build profile, but /Oxs is being used here for a good reason (i.e. to reduce system executable size and free up more memory space for user applications). This is especially important because OpenNT-MinKernel is supposed to target legacy systems with limited amount of memory available.

The root cause of this problem is that OpenNT-MinKernel's crts do not implement __SEH_prolog and __SEH_epilog functions, and in order to resolve this issue, it is necessary to add these functions to the crts. I will create a separate issue addressing this.
